language: go

go:
  - 1.12.x

env:
  - CODECOV_TOKEN="41e2a23e-79bc-4ab4-b8e0-4f7d09458d91"
before_install:
  - sudo add-apt-repository ppa:jonathonf/python-3.6 -y
  - sudo apt-get update
  - sudo apt install python3.6 -y

script:
  - chmod 000 ecosysboard/config/samples/not_good_rights_config.json
  - go test -json ./... > tests_log.json
  - bash scripts/coverage.sh
  - chmod 644 ecosysboard/config/samples/not_good_rights_config.json

after_script:
  - curl -s https://report.ci/upload.py | python3.6 - --include='*.json' --framework=go
  - bash <(curl -s https://codecov.io/bash)