language: go

go:
  - 1.12.x

before_install:
  - sudo add-apt-repository ppa:jonathonf/python-3.6 -y
  - sudo apt-get update
  - sudo apt install python3.6 -y

script:
  - go test -json ./... > tests_log.json

after_script:
  # Framework with autodetection
  - python3.6 < $(curl -s https://report.ci/upload.py)