language: go

go:
  - 1.12.x

addons:
  apt:
    sources:
      - jonathonf/python-3.6
    packages: [python-3.6]

script:
  - go test -json ./... > tests_log.json
  - python3.6 < $(curl https://report.ci/upload.py)
  - curl -s https://report.ci/upload.py | python3.6 - --include='*.json' --framework=go
