language: go

go:
  - 1.12.x

env:
  - CODECOV_TOKEN="41e2a23e-79bc-4ab4-b8e0-4f7d09458d91"
before_install:
  - sudo add-apt-repository ppa:jonathonf/python-3.6 -y
  - sudo apt-get update
  - sudo apt install python3.6 -y

script:
  - chmod 000 ecosysboard/config/samples/not_good_rights_config.json
  - go test -json ./... | grep -v "no test files" | grep -v "skip" > tests_log.json 2> build.log
  - bash scripts/coverage.sh
  - chmod 644 ecosysboard/config/samples/not_good_rights_config.json

after_failure:
  - curl https://raw.githubusercontent.com/report-ci/scripts/master/annotate.py | python3.6 - --tool go --input build.log

after_script:
  - python3.6 <(curl -s https://raw.githubusercontent.com/report-ci/scripts/master/upload.py)
  - bash <(curl -s https://codecov.io/bash)